---
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        permissions:
            checks: write
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: Floby/jest-coverage-report-action@main
              with:
                annotations: 'changed-coverage'
